const images = {
    logo: require('./img/logo.png'),
    heroBG: require('./img/hero-bg.webp'),
    heroBG2: require('./img/hero-bg-2.webp'),
    heroBG3: require('./img/new-banner.webp'),
    bottomBanner: require('./img/new-footer.webp'),
    qrimg: require('./img/Button-cuadrado.webp'),
    girlBanner: require('./img/girl-and-wallet.webp'),
    secondaryImageGroup: require('./img/Group-girl-present.webp'),
    alternativeBannerIMG: require("./img/baloon.webp"),
    first_girl: require('./img/girl-2.png'),
    second_girl: require('./img/pre-footer-img.png'),
    third_girl: require('./img/girl.png'),
    heart: require('./img/heart.svg'),
    rocket: require('./img/heart.svg'),
    graph: require('./img/heart.svg'),
    magic: require('./img/heart.svg'),
    user_men: require('./img/heart.svg'),
    magnifier: require('./img/heart.svg'),
    chat: require('./img/heart.svg'),
    banner2: require('./img/banner-img.png'),
    app_store: require('./img/app-store.png'),
    google_play: require('./img/google-play.png'),
    iphone: require('./img/iphone-1.png'),
    result_right: require('./img/Result_RightArrow.png'),
    result_up: require('./img/Result_UpArrow.png'),
    result_side: require('./img/Result_SideArrow.png'),
    fashionMobile_bottomLeft: require('./img/fashion_bottomLeft.png'),
    fashionMobile_bottomRight: require('./img/fashion_bottomRight.png'),
    fashionMobile_topRight: require('./img/fashion_topRight.png'),
    fashionMobile_topLeft: require('./img/fashion_topLeft.png'),
    restraMobile_bottomLeft: require('./img/restra_bottomLeft.png'),
    restraMobile_bottomRight: require('./img/restra_bottomRight.png'),
    restraMobile_topRight: require('./img/restra_topRight.png'),
    restraMobile_topLeft: require('./img/restra_topLeft.png'),
    tabletSlide1: require('./img/tablet-fidelity.png'),
    tabletSlide2: require('./img/tablet2.png'),
    tabletSlide3: require('./img/tablet3.png'),
    tabletSlide4: require('./img/tablet functions.png'),
    iphone15_1: require('./img/iPhone 15.png'),
    iphone15_2: require('./img/iPhone 15 1.png'),
    iphone15_3: require('./img/iPhone 15 2.png'),
    iphone15_4: require('./img/iPhone 15 3.png'),
    iphone12_1: require('./img/iPhone 12 Pro.png'),
    iphone12_2: require('./img/iPhone 12 Pro 2.png'),
    iphone12_3: require('./img/iphone 12 Pro 3.png'),
    adquisitionTablet1: require('./img/Tablet-Mockup-1 1 1.png'),
    adquisitionTablet2: require('./img/Tablet-Mockup-1 1 2.png'),
    adquisitionTablet3: require('./img/Tablet-Mockup-1 1 3.png'),
    bannerBG1: require('./img/Group 35474.png'),
    bannerBG2: require('./img/Group 35475.png'),
    bannerBG3: require('./img/cashier.png'),
    semifooter1: require('./img/man 1.png'),
    semifooter2: require('./img/Group 35473.png'),
    semifooterVector1: require('./img/Vector 210.png'),
    semifooterVector2: require('./img/Vector 211.png'),
    heart2: require('./img/Vector 218.png'),
    mobileGuy: require('./img/Group girl present (1).png'),
    mobileGirl: require('./img/girl and wallet (1).png'),
    plane: require('./img/plane.png')
}

export default images